openapi: 3.0.1
info:
  title: My Blog App API
  version: 1.0.0
  description: An API for managing blog posts and comments.

servers:
  - url: http://localhost:3000

paths:
  /api/v1/posts:
    get:
      summary: Get a list of posts belonging to the current user.
      description: Returns a list of posts authored by the currently authenticated user.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error


  /api/v1/posts/{id}/comments:
    get:
      summary: Get a list of comments for current post.
      description: Returns a list of comment writed for the post.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error    

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        photo:
          type: string
        bio:
          type: string
        post_counters:
          type: integer
        created_at:
          type: datetime
        updated_at:
          type: datetime
        email:
          type: string
        encrypted_password:
          type: string


    Post:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        text:
          type: string
        comments_counter:
          type: integer
        likes_counter:
          type: integer
        author_id:
          $ref: '#/components/schemas/User'
    
    Comment:
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        created_at:
          type: string
        updated_at:
          type: integer
        author_id:
          $ref: '#/components/schemas/User'
        post_id:
          $ref: '#/components/schemas/Post'

        

securitySchemes:
  apiKeyAuth:
    type: apiKey
    in: header
    name: Authorization
    description: Provide your JWT token in the format 'Bearer TOKEN' for authentication.

security:
  - apiKeyAuth: []

